### ISSUE TITLE
Your first issue...

### ISSUE THREAD

**Issue by Martii** [Vadorequest/fb-adblock-timeline#3]
Per [https://openuserjs.org/scripts/Vadorequest/Facebook_AdBlock_for_your_Timeline/issues/IMPORTANT_-_Post_issues_on_Github!](https://openuserjs.org/scripts/Vadorequest/Facebook_AdBlock_for_your_Timeline/issues/IMPORTANT_-_Post_issues_on_Github!) it is strongly suggested to use [`@supportURL`](https://sourceforge.net/p/greasemonkey/wiki/Metadata_Block/#supporturl) in your UserScript metadata block. This is supported just about everywhere including OUJS. e.g.

``` js
// @supportURL   https://github.com/Vadorequest/fb-adblock-timeline/issues
```

Secondly if there is a TOS issue we will attempt to make an effort to contact you at the `@supportURL`... however if you do not respond then the OUJS issue tracker will be used _(sometimes at the same time)_... so ensure that you do check on occasion.

Thanks,
OUJS Admin

**Comment by Vadorequest** [comment]
Thank you! I'll add it right away :)
